CREATE TABLE IF NOT EXISTS dim_date (
    date_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    month_name TEXT NOT NULL,
    day SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    day_name TEXT NOT NULL,
    week_of_year SMALLINT NOT NULL CHECK (week_of_year BETWEEN 1 AND 53),
    is_weekend BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_geolocation (
    geolocation_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zip_code_prefix INTEGER NOT NULL UNIQUE,
    city TEXT,
    state CHAR(2),
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10, 6),
    source_row_count INTEGER NOT NULL DEFAULT 1 CHECK (source_row_count > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT NOT NULL UNIQUE,
    customer_unique_id TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city TEXT,
    customer_state CHAR(2),
    geolocation_sk INTEGER REFERENCES dim_geolocation (geolocation_sk),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_product (
    product_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL UNIQUE,
    product_category_name TEXT,
    product_category_name_english TEXT,
    product_name_length INTEGER,
    product_description_length INTEGER,
    product_photos_qty INTEGER,
    product_weight_g NUMERIC(12, 2),
    product_length_cm NUMERIC(12, 2),
    product_height_cm NUMERIC(12, 2),
    product_width_cm NUMERIC(12, 2),
    product_volume_cm3 NUMERIC(18, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_seller (
    seller_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id TEXT NOT NULL UNIQUE,
    seller_zip_code_prefix INTEGER,
    seller_city TEXT,
    seller_state CHAR(2),
    geolocation_sk INTEGER REFERENCES dim_geolocation (geolocation_sk),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_payment_summary (
    payment_summary_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    payment_count INTEGER NOT NULL DEFAULT 0 CHECK (payment_count >= 0),
    payment_type_count INTEGER NOT NULL DEFAULT 0 CHECK (payment_type_count >= 0),
    primary_payment_type TEXT,
    max_payment_installments INTEGER CHECK (max_payment_installments IS NULL OR max_payment_installments >= 0),
    total_payment_value NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_payment_value >= 0),
    has_voucher BOOLEAN NOT NULL DEFAULT false,
    has_credit_card BOOLEAN NOT NULL DEFAULT false,
    has_boleto BOOLEAN NOT NULL DEFAULT false,
    has_debit_card BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_review (
    review_sk INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    review_id TEXT,
    review_score SMALLINT CHECK (review_score BETWEEN 1 AND 5),
    review_comment_title TEXT,
    review_comment_message TEXT,
    review_creation_date TIMESTAMPTZ,
    review_answer_timestamp TIMESTAMPTZ,
    review_response_days INTEGER,
    review_count INTEGER NOT NULL DEFAULT 1 CHECK (review_count > 0),
    is_canonical_review BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fact_order_items (
    order_item_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL,
    order_item_id INTEGER NOT NULL,
    customer_sk INTEGER NOT NULL REFERENCES dim_customer (customer_sk),
    product_sk INTEGER NOT NULL REFERENCES dim_product (product_sk),
    seller_sk INTEGER NOT NULL REFERENCES dim_seller (seller_sk),
    payment_summary_sk INTEGER NOT NULL REFERENCES dim_payment_summary (payment_summary_sk),
    review_sk INTEGER REFERENCES dim_review (review_sk),
    customer_geolocation_sk INTEGER REFERENCES dim_geolocation (geolocation_sk),
    seller_geolocation_sk INTEGER REFERENCES dim_geolocation (geolocation_sk),
    purchase_date_sk INTEGER NOT NULL REFERENCES dim_date (date_sk),
    approved_date_sk INTEGER REFERENCES dim_date (date_sk),
    delivered_carrier_date_sk INTEGER REFERENCES dim_date (date_sk),
    delivered_customer_date_sk INTEGER REFERENCES dim_date (date_sk),
    estimated_delivery_date_sk INTEGER REFERENCES dim_date (date_sk),
    order_status TEXT NOT NULL,
    order_purchase_timestamp TIMESTAMPTZ NOT NULL,
    order_approved_at TIMESTAMPTZ,
    order_delivered_carrier_date TIMESTAMPTZ,
    order_delivered_customer_date TIMESTAMPTZ,
    order_estimated_delivery_date TIMESTAMPTZ NOT NULL,
    shipping_limit_date TIMESTAMPTZ NOT NULL,
    product_revenue NUMERIC(14, 2) NOT NULL CHECK (product_revenue >= 0),
    freight_value NUMERIC(14, 2) NOT NULL CHECK (freight_value >= 0),
    total_item_value NUMERIC(14, 2) NOT NULL CHECK (total_item_value >= 0),
    delivery_days INTEGER,
    estimated_delivery_days INTEGER,
    delay_days INTEGER,
    is_late BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_id, order_item_id)
);
